In [264]:
# Importing the required libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [265]:
# Importing the dataset

train=pd.read_csv("train.csv")
test=pd.read_csv("test.csv")

In [266]:
train["Gender"]=train["Gender"].astype("category")
train["Region_Code"]=train.Region_Code.astype("int")
train.Vehicle_Age=train.Vehicle_Age.astype("category")
train.Vehicle_Damage=train.Vehicle_Damage.astype('category')
train.Policy_Sales_Channel=train.Policy_Sales_Channel.astype('int')

train.drop(columns="id",inplace=True)

train["Region_Code"]=train["Region_Code"].astype('category')
train["Policy_Sales_Channel"]=train["Policy_Sales_Channel"].astype('category')

In [267]:
test["Gender"]=train["Gender"].astype("category")
test["Region_Code"]=test.Region_Code.astype("int")
test.Vehicle_Age=test.Vehicle_Age.astype("category")
test.Vehicle_Damage=test.Vehicle_Damage.astype('category')
test.Policy_Sales_Channel=test.Policy_Sales_Channel.astype('int')

test.drop(columns="id",inplace=True)

test["Region_Code"]=test["Region_Code"].astype('category')
test["Policy_Sales_Channel"]=test["Policy_Sales_Channel"].astype('category')

In [268]:
train

Gender  Age  Driving_License Region_Code  Previously_Insured  \
0         Male   44                1          28                   0   
1         Male   76                1           3                   0   
2         Male   47                1          28                   0   
3         Male   21                1          11                   1   
4       Female   29                1          41                   1   
...        ...  ...              ...         ...                 ...   
381104    Male   74                1          26                   1   
381105    Male   30                1          37                   1   
381106    Male   21                1          30                   1   
381107  Female   68                1          14                   0   
381108    Male   46                1          29                   0   

       Vehicle_Age Vehicle_Damage  Annual_Premium Policy_Sales_Channel  \
0        > 2 Years            Yes         40454.0                   26   
1         1-2 Year             No         33536.0                   26   
2        > 2 Years            Yes         38294.0                   26   
3         < 1 Year             No         28619.0                  152   
4         < 1 Year             No         27496.0                  152   
...            ...            ...             ...                  ...   
381104    1-2 Year             No         30170.0                   26   
381105    < 1 Year             No         40016.0                  152   
381106    < 1 Year             No         35118.0                  160   
381107   > 2 Years            Yes         44617.0                  124   
381108    1-2 Year             No         41777.0                   26   

        Vintage  Response  
0           217         1  
1           183         0  
2            27         1  
3           203         0  
4            39         0  
...         ...       ...  
381104       88         0  
381105      131         0  
381106      161         0  
381107       74         0  
381108      237         0  

[381109 rows x 11 columns]

In [269]:
test

Gender  Age  Driving_License Region_Code  Previously_Insured  \
0         Male   25                1          11                   1   
1         Male   40                1          28                   0   
2         Male   47                1          28                   0   
3         Male   24                1          27                   1   
4       Female   27                1          28                   1   
...        ...  ...              ...         ...                 ...   
127032    Male   26                1          37                   1   
127033    Male   38                1          28                   0   
127034  Female   21                1          46                   1   
127035    Male   71                1          28                   1   
127036    Male   41                1          29                   1   

       Vehicle_Age Vehicle_Damage  Annual_Premium Policy_Sales_Channel  \
0         < 1 Year             No         35786.0                  152   
1         1-2 Year            Yes         33762.0                    7   
2         1-2 Year            Yes         40050.0                  124   
3         < 1 Year            Yes         37356.0                  152   
4         < 1 Year             No         59097.0                  152   
...            ...            ...             ...                  ...   
127032    < 1 Year             No         30867.0                  152   
127033    1-2 Year            Yes         28700.0                  122   
127034    < 1 Year             No         29802.0                  152   
127035    1-2 Year             No         62875.0                   26   
127036    1-2 Year             No         27927.0                  124   

        Vintage  
0            53  
1           111  
2           199  
3           187  
4           297  
...         ...  
127032       56  
127033      165  
127034       74  
127035      265  
127036      231  

[127037 rows x 10 columns]

In [270]:
count_1=pd.DataFrame(train[train.Response==1].groupby("Policy_Sales_Channel").count()["Response"])
count_1=count_1.sort_values("Response",ascending=False).reset_index()

In [271]:
count_0=pd.DataFrame(train[train.Response==0].groupby("Policy_Sales_Channel").count()["Response"])
count_0=count_0.sort_values("Response",ascending=False).reset_index()

In [272]:
merged=count_1.merge(count_0,on="Policy_Sales_Channel")
merged["Ratio"]=merged["Response_x"]/merged["Response_y"]
merged.sort_values("Ratio",ascending=False).head(10)
merged.loc[merged["Ratio"]>0.6,"Ratio"]=0
merged.sort_values("Ratio",ascending=False).head(10)

merged=merged.loc[:,["Policy_Sales_Channel","Ratio"]]
merged

Policy_Sales_Channel     Ratio
0                     26  0.249040
1                    124  0.233271
2                    152  0.029467
3                    156  0.274629
4                    157  0.366871
..                   ...       ...
150                  115  0.000000
151                  117  0.000000
152                  118  0.000000
153                   34  0.000000
154                  102  0.000000

[155 rows x 2 columns]

In [273]:
train.dtypes

Gender                  category
Age                        int64
Driving_License            int64
Region_Code             category
Previously_Insured         int64
Vehicle_Age             category
Vehicle_Damage          category
Annual_Premium           float64
Policy_Sales_Channel    category
Vintage                    int64
Response                   int64
dtype: object

In [274]:
train=train.merge(merged,on="Policy_Sales_Channel",how="left")
test=test.merge(merged,on="Policy_Sales_Channel",how="left")

In [281]:
train

Gender  Age  Driving_License Region_Code  Previously_Insured  \
0         Male   44                1          28                   0   
1         Male   76                1           3                   0   
2         Male   47                1          28                   0   
3         Male   21                1          11                   1   
4       Female   29                1          41                   1   
...        ...  ...              ...         ...                 ...   
381104    Male   74                1          26                   1   
381105    Male   30                1          37                   1   
381106    Male   21                1          30                   1   
381107  Female   68                1          14                   0   
381108    Male   46                1          29                   0   

       Vehicle_Age Vehicle_Damage  Annual_Premium Policy_Sales_Channel  \
0        > 2 Years            Yes         40454.0                   26   
1         1-2 Year             No         33536.0                   26   
2        > 2 Years            Yes         38294.0                   26   
3         < 1 Year             No         28619.0                  152   
4         < 1 Year             No         27496.0                  152   
...            ...            ...             ...                  ...   
381104    1-2 Year             No         30170.0                   26   
381105    < 1 Year             No         40016.0                  152   
381106    < 1 Year             No         35118.0                  160   
381107   > 2 Years            Yes         44617.0                  124   
381108    1-2 Year             No         41777.0                   26   

        Vintage  Response     Ratio  
0           217         1  0.249040  
1           183         0  0.249040  
2            27         1  0.249040  
3           203         0  0.029467  
4            39         0  0.029467  
...         ...       ...       ...  
381104       88         0  0.249040  
381105      131         0  0.029467  
381106      161         0  0.022296  
381107       74         0  0.233271  
381108      237         0  0.249040  

[381109 rows x 12 columns]

In [285]:
test[test["Ratio"].isnull()]
test.loc[test["Ratio"].isnull(),"Ratio"]=test["Ratio"].mean()

In [286]:
train.drop(columns=["Region_Code","Policy_Sales_Channel"],inplace=True)
test.drop(columns=["Region_Code","Policy_Sales_Channel"],inplace=True)

In [287]:
train=pd.get_dummies(train,drop_first=True)
train

Age  Driving_License  Previously_Insured  Annual_Premium  Vintage  \
0        44                1                   0         40454.0      217   
1        76                1                   0         33536.0      183   
2        47                1                   0         38294.0       27   
3        21                1                   1         28619.0      203   
4        29                1                   1         27496.0       39   
...     ...              ...                 ...             ...      ...   
381104   74                1                   1         30170.0       88   
381105   30                1                   1         40016.0      131   
381106   21                1                   1         35118.0      161   
381107   68                1                   0         44617.0       74   
381108   46                1                   0         41777.0      237   

        Response     Ratio  Gender_Male  Vehicle_Age_< 1 Year  \
0              1  0.249040            1                     0   
1              0  0.249040            1                     0   
2              1  0.249040            1                     0   
3              0  0.029467            1                     1   
4              0  0.029467            0                     1   
...          ...       ...          ...                   ...   
381104         0  0.249040            1                     0   
381105         0  0.029467            1                     1   
381106         0  0.022296            1                     1   
381107         0  0.233271            0                     0   
381108         0  0.249040            1                     0   

        Vehicle_Age_> 2 Years  Vehicle_Damage_Yes  
0                           1                   1  
1                           0                   0  
2                           1                   1  
3                           0                   0  
4                           0                   0  
...                       ...                 ...  
381104                      0                   0  
381105                      0                   0  
381106                      0                   0  
381107                      1                   1  
381108                      0                   0  

[381109 rows x 11 columns]

In [288]:
test=pd.get_dummies(test,drop_first=True)
test

Age  Driving_License  Previously_Insured  Annual_Premium  Vintage  \
0        25                1                   1         35786.0       53   
1        40                1                   0         33762.0      111   
2        47                1                   0         40050.0      199   
3        24                1                   1         37356.0      187   
4        27                1                   1         59097.0      297   
...     ...              ...                 ...             ...      ...   
127032   26                1                   1         30867.0       56   
127033   38                1                   0         28700.0      165   
127034   21                1                   1         29802.0       74   
127035   71                1                   1         62875.0      265   
127036   41                1                   1         27927.0      231   

           Ratio  Gender_Male  Vehicle_Age_< 1 Year  Vehicle_Age_> 2 Years  \
0       0.029467            1                     1                      0   
1       0.128531            1                     0                      0   
2       0.233271            1                     0                      0   
3       0.029467            1                     1                      0   
4       0.029467            0                     1                      0   
...          ...          ...                   ...                    ...   
127032  0.029467            1                     1                      0   
127033  0.209501            1                     0                      0   
127034  0.029467            0                     1                      0   
127035  0.249040            1                     0                      0   
127036  0.233271            1                     0                      0   

        Vehicle_Damage_Yes  
0                        0  
1                        1  
2                        1  
3                        1  
4                        0  
...                    ...  
127032                   0  
127033                   1  
127034                   0  
127035                   0  
127036                   0  

[127037 rows x 10 columns]

In [289]:
X_train=train.drop(columns="Response")
y_train=train["Response"]

In [290]:
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()

scaler.fit(X_train)
X_train_scaled=pd.DataFrame(scaler.transform(X_train),columns=X_train.columns)
X_test_scaled=pd.DataFrame(scaler.transform(test),columns=test.columns)

## Logistic Regression

### Weight Parameter used (X_train)

In [298]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

scores=cross_val_score(LogisticRegression(class_weight="balanced",random_state=40),X_train,y_train,scoring='f1',cv=10)

scores

array([0.40285017, 0.40579295, 0.40314585, 0.40410403, 0.40179252,
       0.40553173, 0.40299151, 0.23803531, 0.40437211, 0.40125451])

In [21]:
scores.mean()

0.8073761192807103

In [23]:
logreg=LogisticRegression(class_weight='balanced',random_state=40)
logreg.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight='balanced', dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=40, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [24]:
y_train_pred=logreg.predict(X_train)

In [25]:
y_test_pred=logreg.predict(test)

In [26]:
pd.Series(y_test_pred).value_counts()

0    72066
1    54971
dtype: int64

In [28]:
sub1_df=pd.DataFrame({"id":pd.read_csv("test.csv")["id"],"Response":y_test_pred})
sub1_df.to_csv("submission1_A.csv",index=False)

### Weight Parameter used (X_train_scaled)

In [301]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

scores=cross_val_score(LogisticRegression(class_weight="balanced",random_state=40),X_train_scaled,y_train,scoring='roc_auc',cv=10,n_jobs=-1)

scores

array([0.84425249, 0.84408443, 0.84493936, 0.84414579, 0.84083817,
       0.84371124, 0.84401748, 0.84276554, 0.84476039, 0.83885945])

In [302]:
scores.mean()

0.843237432644884

In [293]:
logreg=LogisticRegression(class_weight='balanced',n_jobs=-1)
logreg.fit(X_train_scaled,y_train)

LogisticRegression(C=1.0, class_weight='balanced', dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='auto', n_jobs=-1, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [294]:
y_train_pred=logreg.predict(X_train_scaled)

In [295]:
y_test_pred=logreg.predict(X_test_scaled)

In [296]:
pd.Series(y_test_pred).value_counts()

0    71043
1    55994
dtype: int64

In [297]:
sub2_df=pd.DataFrame({"id":pd.read_csv("test.csv")["id"],"Response":y_test_pred})
sub2_df.to_csv("submission2_B.csv",index=False)

### Changing Cutoffs

In [309]:
y_test_prob=logreg.predict_proba(test)
y_test_prob

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]])

### Regularization

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

In [13]:
lambdas=[0.001,0.01,0.1,1,10,100,1000,10000]

In [14]:
means=[]
stds=[]

for i in lambdas:
    scores=cross_val_score(LogisticRegression(class_weight="balanced",random_state=40,C=i,n_jobs=-1),X_train_scaled,y_train,scoring='roc_auc',cv=5)
    
    means.append(scores.mean())
    stds.append(scores.std())

KeyboardInterrupt: 

In [ ]:
df=pd.DataFrame({"i":lambdas,"mean":means,"std":stds})
df.head(10)

In [ ]:
fig,ax=plt.subplots(1,2,figsize=(14,7))
sns.lineplot(x=lambdas,y=means,label="Mean",ax=ax[0])
sns.lineplot(x=lambdas,y=stds,label="Std",ax=ax[1])

In [32]:
logreg=LogisticRegression(class_weight="balanced",random_state=40,C=10,n_jobs=-1)
logreg.fit(X_train_scaled,y_train)

LogisticRegression(C=10, class_weight='balanced', dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='auto', n_jobs=-1, penalty='l2',
                   random_state=40, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [33]:
y_train_pred=logreg.predict(X_train_scaled)

In [34]:
y_test_pred=logreg.predict(X_test_scaled)

In [35]:
pd.Series(y_test_pred).value_counts()

0    66774
1    60263
dtype: int64

In [30]:
sub5_df=pd.DataFrame({"id":pd.read_csv("test.csv")["id"],"Response":y_test_pred})
sub5_df.to_csv("submission5_A.csv",index=False)

In [36]:
logreg.coef_

array([[-1.47544166,  1.2110478 , -3.9872713 ,  1.63057025, -0.01288716,
         0.11066402, -1.20346992,  0.22134474,  2.03289825]])

In [31]:
logreg.coef_

array([[-1.47647243,  1.20625212, -3.98569261,  1.6347821 , -0.01297498,
         0.11051677, -1.20356023,  0.22116275,  2.03262937]])

## KNN

In [76]:
from sklearn.neighbors import KNeighborsClassifier

In [77]:
knn=KNeighborsClassifier()

In [78]:
scores=cross_val_score(KNeighborsClassifier(),X_train_scaled,y_train,scoring='roc_auc',cv=5,n_jobs=-1)
scores

array([0.74752835, 0.74657946, 0.74813071, 0.74564059, 0.75293851])